In [1]:
# Setup - copy-pasted from 2A

# Python ≥3.9 is required
import sys
assert sys.version_info >= (3, 9)

# Scikit-Learn ≥1.0 is required
import sklearn
assert sklearn.__version__ >= "1.0"

# Common imports
import numpy as np
import pandas as pd

# To plot pretty figures
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Precision options
np.set_printoptions(precision=2)
pd.options.display.float_format = '{:.3f}'.format

# Statistical analysis and testing
from statsmodels.formula.api import ols
import statsmodels.api as sm

# Ignore useless warnings (see SciPy issue #5998 and seaborn/matplotlib bug)
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")
warnings.filterwarnings(action="ignore", message="The figure layout has changed to tight")

import json
import datetime

In [2]:
#f=open("default-cards-20240806090619.json")
#raw_data = json.load(f)
# raw_data[0]

In [3]:
todays_date = datetime.datetime(year=2025,month=12,day=14)

Features the program gets NOTHING out of:
    "object", 
    "oracle_id", 
    "arena_id", 
    "multiverse_ids", 
    "tcgplayer_id", 
    "cardmarket_id", 
    "uri", 
    "scryfall_uri", 
    "oracle_text",
    "image_status",
    "image_uris",
    "set_name",
    "set_uri",
    "set_search_uri",
    "scryfall_set_uri",
    "rulings_uri",
    "prints_search_uri",
    "preview",
    "related_uris",
    "purchase_uris",
    "flavor_text",
    "usd",
    "usd_foil",
    "usd_etched",
    "eur",
    "eur_foil",
    "highres_image"
\+ maybe some more

Ordinal features I want to give the program:
Rarity

Categorical features I want to give the program:
Colors

There are some features that ML won't make head or tail of (eg. various URIs, oracle_text)

Some features that I deliberately don't want to give to the program (eg. card prices in paper)

Some features I'm interested in from a data analysis perspective, but will very likely be useless for determining price (eg. )

In [4]:
#df = pd.DataFrame.from_dict(raw_data)

Legalities:

Some formats are simple binaries. These are:
- vintage - legal or restricted
- legacy - legal or banned
- penny - legal or not_legal
- commander - legal or banned

(((((Some formats are *effectively* binaries. These are:
- duel - legal or banned (ignore restricted, it's just "is this creature legendary))))))

The rest are more complicated. 

(not_legal, legal, banned) formats:
- future
- standard
- pioneer
- modern
- pauper

(not_legal, legal, restricted) formats:


These need to have two variables:
Binary:
- printed_into_{format} -> = not({format}="not_legal")

Then "ternary" - 0, 1 or NaN (use a mean imputer when doing ML)
- banned_in_{format} -> (banned/restricted)=1, legal=0, not_legal=NaN

4 categories:
paupercommander -> (not_legal, legal, restricted, banned)
Just ignore restricted (it's just the same as "is an uncommon creature")

I think I need to take a step back and ignore legality for a bit

# Description of features
### Describe every feature in detail

DATA CLEANING

Decide to only care about MTGO prices etc

"object" is never anything except "card" - useless
Remove all Un-set cards I think

Target variable: "prices" -> "tix" 
(MTGO economy uses tix as a currency - 1 tix = 1 US dollar)
Remove all prices except for tix ()

Variables to keep:
MTGO ID 
(Name? I want it for readability but it's useless for the algorithm)


Data cleaning:
Remove anything where "mtgo" not in "games" (ie. Alchemy cards)
Remove Un-set cards (I don't wanna deal with CMC 0.5 or 1,000,000)
Potentially remove P9 as outliers?




Problems for data representation: 
Unpack legalities and prices
(Possibly don't give it legality in "penny" though - dead giveaway!)
Keywords: One hot encoding again but that's gonna get hella annoying - consider just teaching it the most common ones?
Prices: Just keep "tix" (if model is very very shit, consider letting it have other prices lol)

Categorical things to one-hot encode, in order of probable utility to the algorithm:
Format legality - Legal, Not Legal, Banned, Restricted (maybe remove "penny" if I'm feeling mean, but start by not doing that)
Rarity - common, uncommon, rare, mythic, special, bonus (note: bonus is literally just the power 9!)
(Don't bother teaching it colours I think)
Keywords


Problems to solve for the algorithm:

I'd like it to be able to understand keywords - ie. if a card has flying, I want the algorithm to take that into account. ATM keywords are stored in a list - hard for ML to understand!

In [5]:
#csv_cards = pd.DataFrame(json.load(f))
#csv_cards

# Order of operations:
# 1: expand important dict features to columns
# 2: remove outlier rows
# 3: remove junk columns
# 4. onehot-encode things I want (eg. keywords)

In [6]:
import scryfall_preprocessing as sf

In [7]:
from importlib import reload
reload(sf)

In [8]:
df = sf.get_cards()
df

,object,id,oracle_id,multiverse_ids,mtgo_id,tcgplayer_id,cardmarket_id,name,lang,released_at,...,life_modifier,hand_modifier,attraction_lights,color_indicator,flavor_name,content_warning,variation_of,printed_type_line,printed_text,defense
0,card,a471b306-4941-4e46-a0cb-d92895c16f8a,00037840-6089-42ec-8c5c-281f9f474504,[692174],137223.000,615195.000,807933.000,"Nissa, Worldsoul Speaker",en,2025-02-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,6b7baaa7-67f2-4902-a4c1-761d58cce1d4,000492bf-7eaa-4939-a51c-4eef74e4c1d1,[],NaN,NaN,NaN,Mine Security,en,2025-08-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,86bf43b1-8d4e-4759-bb2d-0b2e03ba7012,0004ebd0-dfd6-4276-b4a6-de0003e94237,[15862],15870.000,3094.000,3081.000,Static Orb,en,2001-04-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,7050735c-b232-47a6-a342-01795bfd0d46,0006faf6-7a61-426c-9034-579f2cfcfa83,[370780],49283.000,69965.000,262945.000,Sensory Deprivation,en,2013-07-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,9c5e9b5f-6e71-4afc-abbd-ba4c788a3240,00078ea3-0462-4a6e-b7b1-25fea012b2b7,[],NaN,NaN,NaN,Kavaron Consumed,en,2025-08-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39051,card,d6695fa8-881c-407c-91d9-3ac770372d35,fffa9334-3576-4f70-9605-2ad062cdbc69,[430770],64646.000,136683.000,298834.000,Without Weakness,en,2017-07-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39052,card,4d5edf4f-5695-42fc-9e57-c4faef60fbc3,fffaa634-42a0-4038-b027-24f28754fec7,[571548],101914.000,276869.000,665173.000,Firesong and Sunspeaker,en,2022-07-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39053,card,22a6a5f1-1405-4efb-af3e-e1f58d664e99,fffcb71f-e802-436e-917d-eaa6607ab74f,"[503766, 503767]",87643.000,230214.000,530502.000,"Toralf, God of Fury // Toralf's Hammer",en,2021-02-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39054,card,09f06f55-7918-46c4-80ff-0bf39e091a4a,fffdc2ac-bde4-4e4c-a5bd-0e6c6e49ad91,[430833],64772.000,132234.000,298282.000,"Samut, the Tested",en,2017-07-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39055,card,1ecc983e-bbe3-4bc1-97e9-e40ead987ef0,ffff90c3-63c4-4dee-a21d-6b2b113f4f80,[625242],114015.000,505126.000,722911.000,Sinew Sliver,en,2023-08-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

All variables I want to one-hot encode:

- Types
- Keywords
- Set code
- Legalities (one for each format GUHHHH)
- Border color


UPDATE: Things I actually care about:
- "power/cmc", "toughness/cmc", "(power+toughness)/cmc" variables?
- RELEVANT keywords only (just the common ones)
- NUMBER of colours
- NUMBER of coloured pips

(note: might be worth using a separate df for just creatures for some of this?)

All variables needing imputation:

- Power
- Toughness
- Mana cost (for transform cards lol)

In [9]:
import scryfall_preprocessing as sf
#import get_scryfall_data

df2 = sf.expand_dict_features(df)
df3 = sf.standard_only(df2)
df4 = sf.drop_junk_features(df3)
#df5 = sf.drop_more_features(df4)
df5 = sf.remove_legalities(df4)
df6 = sf.ordinate_rarities(df5)

In [10]:
df6

,name,released_at,layout,image_updated_at,mana_cost,cmc,type_line,power,toughness,colors,...,penny_rank,resource_id,flavor_name,variation_of,printed_type_line,printed_text,competitivebrawl,tlr,eur,ordinate_rarity
0,"Greta, Sweettooth Scourge",2023-09-08,normal,2026-07-13 03:57:51+00:00,{1}{B}{G},3.000,Legendary Creature — Human Warrior,3,3,"[B, G]",...,4707.000,NaN,NaN,NaN,NaN,NaN,legal,legal,0.16,2
1,Seedship Agrarian,2025-08-01,normal,2026-07-13 01:25:32+00:00,{3}{G},4.000,Creature — Insect Scientist,3,3,[G],...,NaN,2D06A4B98579996F08D6116C41925C4D0680F2FC0B4299...,NaN,NaN,NaN,NaN,legal,not_legal,0.12,2
2,South Wind Avatar,2026-03-06,normal,2026-07-13 00:55:01+00:00,{3}{B},4.000,Creature — Snake Spirit Avatar,3,4,[B],...,5629.000,E6C987508C44DF749E830D21C77DDEB2F6D65A582EFC88...,NaN,NaN,NaN,NaN,legal,not_legal,1.22,3
3,Escape Tunnel,2026-03-06,normal,2026-07-13 00:54:24+00:00,,0.000,Land,NaN,NaN,[],...,673.000,A47EF1D740F848F4362ADE4C265636EE09ECB2A1EF8F8B...,NaN,NaN,NaN,NaN,legal,legal,0.12,1
4,Food Fight,2023-09-08,normal,2026-07-13 03:58:14+00:00,{1}{R},2.000,Enchantment,NaN,NaN,[R],...,6133.000,NaN,NaN,NaN,NaN,NaN,legal,legal,0.12,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,Wildheart Invoker,2024-11-15,normal,2026-07-13 02:15:44+00:00,{2}{G}{G},4.000,Creature — Elf Shaman,4,3,[G],...,15475.000,09E3E9E907C2006CBA299C80D6C81C7C5459EF323AFFE9...,NaN,NaN,NaN,NaN,legal,not_legal,0.14,1
5105,Pummeler for Hire,2026-01-23,normal,2026-07-13 01:00:25+00:00,{4}{G},5.000,Creature — Giant Mercenary,4,4,[G],...,NaN,2AF9AA39B0FAED748F47E8F9B769D760B09FFCC74D0B7F...,NaN,NaN,NaN,NaN,legal,not_legal,0.10,2
5106,Auxiliary Boosters,2025-08-01,normal,2026-07-13 01:26:39+00:00,{4}{W},5.000,Artifact — Equipment,NaN,NaN,[W],...,NaN,D08AE5129952ACC16A999111F183AB945377034198FC3D...,NaN,NaN,NaN,NaN,legal,not_legal,0.06,1
5107,Withering Torment,2026-06-26,normal,2026-07-13 00:40:35+00:00,{2}{B},3.000,Instant,NaN,NaN,[B],...,3845.000,BAB6DF6AFFC6B8CE558D75F54032520EDFC49DD74FAD37...,NaN,NaN,NaN,NaN,legal,legal,1.27,2
5108,The Lion-Turtle,2025-11-21,normal,2026-07-13 01:08:43+00:00,{1}{G}{U},3.000,Legendary Creature — Elder Cat Turtle,3,6,"[G, U]",...,NaN,FBCB75892E7E0911EE18CE08FCD151AD168682FAD8A0A2...,NaN,NaN,NaN,NaN,legal,legal,0.28,3

In [11]:
reload(sf)

In [12]:
df7 = sf.convert_all_to_numbers(df6)

In [13]:
df7

,name,released_at,layout,image_updated_at,mana_cost,type_line,colors,color_identity,keywords,game_changer,...,printed_text,competitivebrawl,tlr,ordinate_rarity,foil,booster,eur,cmc,power,toughness
0,"Greta, Sweettooth Scourge",2023-09-08,normal,2026-07-13 03:57:51+00:00,{1}{B}{G},Legendary Creature — Human Warrior,"[B, G]","[B, G]",[Food],False,...,NaN,legal,legal,2,1,1,1.000,1.000,1.000,1.000
1,Seedship Agrarian,2025-08-01,normal,2026-07-13 01:25:32+00:00,{3}{G},Creature — Insect Scientist,[G],[G],[Landfall],False,...,NaN,legal,not_legal,2,1,1,1.000,1.000,1.000,1.000
2,South Wind Avatar,2026-03-06,normal,2026-07-13 00:55:01+00:00,{3}{B},Creature — Snake Spirit Avatar,[B],[B],[Deathtouch],False,...,NaN,legal,not_legal,3,1,1,1.000,1.000,1.000,1.000
3,Escape Tunnel,2026-03-06,normal,2026-07-13 00:54:24+00:00,,Land,[],[],[],False,...,NaN,legal,legal,1,1,1,1.000,1.000,0.000,0.000
4,Food Fight,2023-09-08,normal,2026-07-13 03:58:14+00:00,{1}{R},Enchantment,[R],[R],[],False,...,NaN,legal,legal,3,1,1,1.000,1.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,Wildheart Invoker,2024-11-15,normal,2026-07-13 02:15:44+00:00,{2}{G}{G},Creature — Elf Shaman,[G],[G],[],False,...,NaN,legal,not_legal,1,1,1,1.000,1.000,1.000,1.000
5105,Pummeler for Hire,2026-01-23,normal,2026-07-13 01:00:25+00:00,{4}{G},Creature — Giant Mercenary,[G],[G],"[Reach, Vigilance, Ward]",False,...,NaN,legal,not_legal,2,1,1,1.000,1.000,1.000,1.000
5106,Auxiliary Boosters,2025-08-01,normal,2026-07-13 01:26:39+00:00,{4}{W},Artifact — Equipment,[W],[W],[Equip],False,...,NaN,legal,not_legal,1,1,1,1.000,1.000,0.000,0.000
5107,Withering Torment,2026-06-26,normal,2026-07-13 00:40:35+00:00,{2}{B},Instant,[B],[B],[],False,...,NaN,legal,legal,2,1,1,1.000,1.000,0.000,0.000
5108,The Lion-Turtle,2025-11-21,normal,2026-07-13 01:08:43+00:00,{1}{G}{U},Legendary Creature — Elder Cat Turtle,"[G, U]","[G, U]","[Reach, Vigilance]",False,...,NaN,legal,legal,3,1,1,1.000,1.000,1.000,1.000

In [14]:
df8 = sf.cut_subtypes(df7)

In [15]:
df8

,name,released_at,layout,image_updated_at,mana_cost,colors,color_identity,keywords,game_changer,variation,...,competitivebrawl,tlr,ordinate_rarity,foil,booster,eur,cmc,power,toughness,types
0,"Greta, Sweettooth Scourge",2023-09-08,normal,2026-07-13 03:57:51+00:00,{1}{B}{G},"[B, G]","[B, G]",[Food],False,False,...,legal,legal,2,1,1,1.000,1.000,1.000,1.000,"[Legendary, Creature]"
1,Seedship Agrarian,2025-08-01,normal,2026-07-13 01:25:32+00:00,{3}{G},[G],[G],[Landfall],False,False,...,legal,not_legal,2,1,1,1.000,1.000,1.000,1.000,[Creature]
2,South Wind Avatar,2026-03-06,normal,2026-07-13 00:55:01+00:00,{3}{B},[B],[B],[Deathtouch],False,False,...,legal,not_legal,3,1,1,1.000,1.000,1.000,1.000,[Creature]
3,Escape Tunnel,2026-03-06,normal,2026-07-13 00:54:24+00:00,,[],[],[],False,False,...,legal,legal,1,1,1,1.000,1.000,0.000,0.000,[Land]
4,Food Fight,2023-09-08,normal,2026-07-13 03:58:14+00:00,{1}{R},[R],[R],[],False,False,...,legal,legal,3,1,1,1.000,1.000,0.000,0.000,[Enchantment]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,Wildheart Invoker,2024-11-15,normal,2026-07-13 02:15:44+00:00,{2}{G}{G},[G],[G],[],False,False,...,legal,not_legal,1,1,1,1.000,1.000,1.000,1.000,[Creature]
5105,Pummeler for Hire,2026-01-23,normal,2026-07-13 01:00:25+00:00,{4}{G},[G],[G],"[Reach, Vigilance, Ward]",False,False,...,legal,not_legal,2,1,1,1.000,1.000,1.000,1.000,[Creature]
5106,Auxiliary Boosters,2025-08-01,normal,2026-07-13 01:26:39+00:00,{4}{W},[W],[W],[Equip],False,False,...,legal,not_legal,1,1,1,1.000,1.000,0.000,0.000,[Artifact]
5107,Withering Torment,2026-06-26,normal,2026-07-13 00:40:35+00:00,{2}{B},[B],[B],[],False,False,...,legal,legal,2,1,1,1.000,1.000,0.000,0.000,[Instant]
5108,The Lion-Turtle,2025-11-21,normal,2026-07-13 01:08:43+00:00,{1}{G}{U},"[G, U]","[G, U]","[Reach, Vigilance]",False,False,...,legal,legal,3,1,1,1.000,1.000,1.000,1.000,"[Legendary, Creature]"

In [16]:
df8.dtypes

name                              object
released_at               datetime64[ns]
layout                            object
image_updated_at     datetime64[ns, UTC]
mana_cost                         object
colors                            object
color_identity                    object
keywords                          object
game_changer                        bool
variation                           bool
set                               object
set_type                          object
watermark                         object
security_stamp                    object
edhrec_rank                      float64
penny_rank                       float64
resource_id                       object
flavor_name                       object
variation_of                      object
printed_type_line                 object
printed_text                      object
competitivebrawl                  object
tlr                               object
ordinate_rarity                    int64
foil                               int64
booster                            int64
eur                              float64
cmc                              float64
power                            float64
toughness                        float64
types                             object
dtype: object

In [17]:
from sklearn.preprocessing import OneHotEncoder
def expand_typeline(data: pd.DataFrame) -> pd.DataFrame:
    engineered_data = data.copy()
    types = engineered_data.types
    relevant_types = ["Creature","Artifact"]
    print("...unfinished!")
    #return engineered_data

In [18]:
#x = expand_typeline(df8)
#x

In [19]:
df8[np.logical_not(df8.colors.notnull())]

,name,released_at,layout,image_updated_at,mana_cost,colors,color_identity,keywords,game_changer,variation,...,competitivebrawl,tlr,ordinate_rarity,foil,booster,eur,cmc,power,toughness,types
88,The Emperor of Palamecia // The Lord Master of...,2025-06-13,transform,2026-07-13 01:36:19+00:00,NaN,NaN,"[R, U]","[Starfall, Transform]",False,False,...,legal,legal,2,1,1,1.000,1.000,0.000,0.000,"[Legendary, Creature, —, Human, Noble, Wizard,..."
235,Treasure Map // Treasure Cove,2023-11-17,transform,2026-07-13 03:35:24+00:00,NaN,NaN,[],"[Transform, Treasure, Scry]",False,False,...,legal,legal,3,1,1,1.000,1.000,0.000,0.000,"[Artifact, //, Land]"
246,Sidequest: Card Collection // Magicked Card,2025-06-13,transform,2026-07-13 01:37:15+00:00,NaN,NaN,[U],"[Flying, Transform, Crew]",False,False,...,legal,not_legal,2,1,1,1.000,1.000,0.000,0.000,"[Enchantment, //, Artifact]"
448,"Matzalantli, the Great Door // The Core",2023-11-17,transform,2026-07-13 03:35:29+00:00,NaN,NaN,[],"[Transform, Fathomless descent]",False,False,...,legal,legal,3,1,1,1.000,1.000,0.000,0.000,"[Legendary, Artifact, //, Legendary, Land]"
488,"Grub, Storied Matriarch // Grub, Notorious Auntie",2026-01-23,transform,2026-07-13 01:01:08+00:00,NaN,NaN,"[B, R]","[Blight, Transform, Menace]",False,False,...,legal,legal,3,1,1,1.000,1.000,0.000,0.000,"[Legendary, Creature, —, Goblin, Warlock, //, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988,Jade Seedstones // Jadeheart Attendant,2023-11-17,transform,2026-07-13 03:35:50+00:00,NaN,NaN,[G],"[Craft, Transform]",False,False,...,legal,not_legal,2,1,1,1.000,1.000,0.000,0.000,"[Artifact, //, Artifact, Creature]"
5052,Unstable Glyphbridge // Sandswirl Wanderglyph,2023-11-17,transform,2026-07-13 03:36:45+00:00,NaN,NaN,[W],"[Flying, Craft, Transform]",False,False,...,legal,not_legal,3,1,1,1.000,1.000,0.000,0.000,"[Artifact, //, Artifact, Creature]"
5054,"Aclazotz, Deepest Betrayal // Temple of the Dead",2023-11-17,transform,2026-07-13 03:36:29+00:00,NaN,NaN,[B],"[Flying, Lifelink, Transform]",False,False,...,legal,not_legal,4,1,1,1.000,1.000,0.000,0.000,"[Legendary, Creature]"
5080,"King T'Challa // Black Panther, Hope Enduring",2026-06-26,modal_dfc,2026-07-13 00:35:11+00:00,NaN,NaN,"[U, W]","[Transform, Double strike, Flash]",False,False,...,legal,not_legal,4,1,1,1.000,1.000,0.000,0.000,"[Legendary, Creature, —, Human, Noble, Hero, /..."
5081,"Eddie Brock // Venom, Lethal Protector",2025-09-26,modal_dfc,2026-07-13 01:15:51+00:00,NaN,NaN,"[B, G, R]","[Transform, Haste, Trample, Menace]",False,False,...,legal,not_legal,4,1,1,1.000,1.000,0.000,0.000,"[Legendary, Creature, —, Human, Hero, Villain,..."

In [20]:
#df8[np.logical_not(df8.edhrec_rank.notnull())]

# Wastes is the only card to not have an "edh_rank"

In [21]:
#df8[np.logical_not(df8.colors.notnull())]  
# 67 of these

#df8[np.logical_or((df8.layout=="modal_dfc"),(df8.layout=="transform"))]   
# also 67 of these!

# They do still have tix/eur and cmc values but don't have various datapoints eg. mana_cost, colors, etc.

In [22]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder(categories='auto')

#train_data_cat = train_data[["zipcode_group"]]
#train_data_cat_1hot = cat_encoder.fit_transform(train_data_cat)
#train_data_cat_1hot

In [23]:
# Need to expand the dict features BEFORE using the transformer, because need to drop the "tix" column before transforming

In [24]:
# from sklearn.base import BaseEstimator, TransformerMixin

# class FeatureEngineeringTransformer(BaseEstimator, TransformerMixin):

#     def transform(self, data, labels=None) -> pd.DataFrame:
#         # let's make a copy of the original dataset
#         engineered_data = data.copy()

#         engineered_data = expand_dict_features(engineered_data) # type: ignore
#         engineered_data = drop_junk_features(engineered_data)
#         engineered_data = clean_dataset(engineered_data)
        


#         return engineered_data

In [25]:
#fe_trf = FeatureEngineeringTransformer()
#fe_trf.transform(df)

In [26]:
#df4.to_clipboard()

# Take a sample, then put it on clipboard

In [27]:
# Variables I want!!

# Number of colors

# power/cmc
# toughness/cmc
# p+t/cmc

In [28]:
def num_colors(data: pd.DataFrame) -> pd.DataFrame:
    engineered_data = data.copy()
    num_colors = engineered_data.colors.str.len()
    engineered_data["num_colors"] = num_colors
    engineered_data = engineered_data.drop(columns="colors")
    return engineered_data

In [29]:
def vars_wrt_cmc(data: pd.DataFrame) -> pd.DataFrame:
    engineered_data = data.copy()
    power, toughness, cmc = engineered_data["power"], engineered_data["toughness"], engineered_data["cmc"]

    p_vs_cmc = (power.div(cmc)).rename("power/cmc")
    t_vs_cmc = (toughness.div(cmc)).rename("toughness/cmc")
    pt_vs_cmc = ((power.add(toughness)).div(cmc)).rename("p+t/cmc")

    engineered_data = engineered_data.join(p_vs_cmc).join(t_vs_cmc).join(pt_vs_cmc)
    return engineered_data

In [30]:
df9 = num_colors(df8)

In [31]:
df9.describe()

,released_at,edhrec_rank,penny_rank,ordinate_rarity,foil,booster,eur,cmc,power,toughness,num_colors
count,5109,5108.000,2738.000,5109.000,5109.000,5109.000,5109.000,5109.000,5109.000,5109.000,5022.000
mean,2025-04-24 15:07:34.492072960,12026.243,6456.660,2.084,1.000,1.000,1.000,1.000,0.578,0.578,1.072
min,2011-04-01 00:00:00,33.000,19.000,1.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000
25%,2024-08-02 00:00:00,6149.000,2832.250,1.000,1.000,1.000,1.000,1.000,0.000,0.000,1.000
50%,2025-06-13 00:00:00,11784.500,5953.000,2.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
75%,2026-03-06 00:00:00,17244.500,9500.750,3.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
max,2026-11-13 00:00:00,31265.000,18271.000,4.000,1.000,1.000,1.000,1.000,1.000,1.000,5.000
std,NaN,7059.648,4269.437,0.940,0.000,0.000,0.000,0.000,0.494,0.494,0.587

In [32]:
df10 = vars_wrt_cmc(df9)

In [33]:
df10

,name,released_at,layout,image_updated_at,mana_cost,color_identity,keywords,game_changer,variation,set,...,booster,eur,cmc,power,toughness,types,num_colors,power/cmc,toughness/cmc,p+t/cmc
0,"Greta, Sweettooth Scourge",2023-09-08,normal,2026-07-13 03:57:51+00:00,{1}{B}{G},"[B, G]",[Food],False,False,woe,...,1,1.000,1.000,1.000,1.000,"[Legendary, Creature]",2.000,1.000,1.000,2.000
1,Seedship Agrarian,2025-08-01,normal,2026-07-13 01:25:32+00:00,{3}{G},[G],[Landfall],False,False,eoe,...,1,1.000,1.000,1.000,1.000,[Creature],1.000,1.000,1.000,2.000
2,South Wind Avatar,2026-03-06,normal,2026-07-13 00:55:01+00:00,{3}{B},[B],[Deathtouch],False,False,tmt,...,1,1.000,1.000,1.000,1.000,[Creature],1.000,1.000,1.000,2.000
3,Escape Tunnel,2026-03-06,normal,2026-07-13 00:54:24+00:00,,[],[],False,False,tmt,...,1,1.000,1.000,0.000,0.000,[Land],0.000,0.000,0.000,0.000
4,Food Fight,2023-09-08,normal,2026-07-13 03:58:14+00:00,{1}{R},[R],[],False,False,woe,...,1,1.000,1.000,0.000,0.000,[Enchantment],1.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,Wildheart Invoker,2024-11-15,normal,2026-07-13 02:15:44+00:00,{2}{G}{G},[G],[],False,False,fdn,...,1,1.000,1.000,1.000,1.000,[Creature],1.000,1.000,1.000,2.000
5105,Pummeler for Hire,2026-01-23,normal,2026-07-13 01:00:25+00:00,{4}{G},[G],"[Reach, Vigilance, Ward]",False,False,ecl,...,1,1.000,1.000,1.000,1.000,[Creature],1.000,1.000,1.000,2.000
5106,Auxiliary Boosters,2025-08-01,normal,2026-07-13 01:26:39+00:00,{4}{W},[W],[Equip],False,False,eoe,...,1,1.000,1.000,0.000,0.000,[Artifact],1.000,0.000,0.000,0.000
5107,Withering Torment,2026-06-26,normal,2026-07-13 00:40:35+00:00,{2}{B},[B],[],False,False,msc,...,1,1.000,1.000,0.000,0.000,[Instant],1.000,0.000,0.000,0.000
5108,The Lion-Turtle,2025-11-21,normal,2026-07-13 01:08:43+00:00,{1}{G}{U},"[G, U]","[Reach, Vigilance]",False,False,tla,...,1,1.000,1.000,1.000,1.000,"[Legendary, Creature]",2.000,1.000,1.000,2.000